
spring:
  data: 
    redis: 
      host: localhost
      port: 6379
      database: 0
  datasource:
    # permanently saving records
    url: jdbc:h2:file:./src/main/resources/db/h2
    driver-class-name: org.h2.Driver
    username: sa
    password: #
    # in order to have embedded and used for temprorary usages
    # generate-unique-name: false
    # name: fum_reservation
  h2:
    console:
      enabled: true
      path: /h2-console
  thymeleaf:
    cache: false
  # current profile for build
  profiles: 
    active: 
    - debug
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 
server:
  port: 443
  ssl:
    enabled: true
    key-store: C:/Users/Asia LAPTOP/springKeys.jks
    key-store-password: esnkh6940285
    key-password: esnkh6940285

logging: 
  level:
    roo:  DEBUG
    org.springframework.security: DEBUG

